FROM alpine AS primerLinux
RUN mkdir 10B
RUN echo "Hola 10B" > 10B/hola.txt

FROM ubuntu:latest as miUbuntu
RUN apt-get -y update; apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash && apt-get -qqy install nodejs
RUN echo "console.log('Hola');" > archivo.js
RUN node archivo.js > log_node.txt
COPY --from=primerLinux 10B/hola.txt /
RUN mkdir proyecto_node
COPY Mathematics.js /proyecto_node
COPY pruebas.test.js /proyecto_node
RUN cd /proyecto_node && npm init --yes
RUN cd /proyecto_node && npm install jest@latest

CMD /bin/bash